"use strict";

// Beginning with a single comma-separated string to get majority of categories populated
var categoriesAsSingleString =
  "A boy’s name, Counties, Things that are cold, School equipment, Teams, Insects, Breakfast foods, Furniture, Tv shows, Things in the ocean, Famous detectives, Product names, Vegetables, Royalty, Things that smell, Occupations, Appliances, Cartoon characters, Birds, Musical groups, Shop names, Things at a football game, Trees, Personality traits, Articles of clothing, Desserts, Car parts, Things found on a map, Athletes, Four-letter words, Things found in the fridge, Farm animals, Units of currency, Things at the seaside, Colours, Tools, Sports, Song titles, Parts of the body, Things that fly, Things that float, Drinks, A girl’s name, TV stars, Items in the kitchen, Villains/monsters, Flowers, Things found on the farm, Sandwiches, Things that you read, World leaders/politicians, School subjects, Excuses for being late, Cocktails, Advertising slogans, Modes of transport, Things in a park, Foreign cities, Stones/gems, Musical instruments, Things that are sticky, Famous landmarks, Cars, Herbs and spices, Bad habits, Cosmetics/toiletries, Celebrities, Cooking utensils, Reptiles/amphibians, Mountains, Leisure activities, Things that fasten, Fictional characters, Actors and actresses, Magazines, Capitals, Sweets, Office equipment, Footwear, Slang words, Things you take on holiday, Things with tails, Sports equipment, Crimes, Singers, Things in the sky, Things found at the bakery, Olympic sports, Fish, Countries, Things that have spots, Historical figures, Things you are afraid of, Terms of measurement, Items in this room, Book titles, Famous bridges, Notorious people, Fruits, Things in the bathroom cabinet, Toys, Household chores, Bodies of water, Authors, Things you communicate by, Weapons, Things that are round, Things associated with exercise, Composers, Mythological characters, Terms of endearment, Dances, Famous paintings, Vehicles, Airlines, Things found at the office, Dairy products, Things that annoy you, Items in your handbag/wallet, Catchphrases, Artists, Battles, Things found in a desk, Holiday locations, Diseases, Words associated with money, Fashion designers, Film titles, Games, Things you can wear, Beers, Things in a circus, Famous females, Breeds of dogs, Things made of metal, Hobbies, Persons in uniform, Things you plug in, Animals, Languages, Things you can find in supermarkets, Charities, Things made of paper, Companies";

// Library becomes array with each element a category as its own string.
// Can be edited with push and splice in-game
// Can be iterated over to dynamically create HTML template (Handlebars) for list structure on page
const Library = categoriesAsSingleString.split(", ");

export { Library };
